### ISSUE TITLE
mlsql 2.1 链接 CDH6.3.2 spark2.4 报错

### ISSUE THREAD

**Issue by JamesBonddu** [byzer-org/kolo-lang#1590]
环境依赖:

在CDH的某一个hdfs的datanode节点部署mlsql.

```sh
mlsql-console-2.1.0

mlsql-engine_2.4-2.1.0

      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.0-cdh6.3.2
      /_/
         
Using Scala version 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_301)
Type in expressions to have them evaluated.
Type :help for more information.

java -version
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

mlsql-engine中jetty版本
<jetty.version>9.2.16.v20160414</jetty.version>
```

mlsql-engine报错:
```sh
java.lang.NoSuchMethodError: org.eclipse.jetty.util.StringUtil.toInt(Ljava/lang/String;)I
        at org.eclipse.jetty.http.HttpParser.handleKnownHeaders(HttpParser.java:854)
        at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:968)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1257)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
21/10/27 20:05:40 WARN thread.QueuedThreadPool: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@5abe6786 in qtp1052247420{STARTED,100<=100<=1000,i=96,q=0}
21/10/27 11:15:12 INFO yarn.SparkRackResolver: Got an error when resolving hostNames. Falling back to /default-rack for all
```

**Comment by chncaesar** [comment]
Please use spark-2.4.3 , spark-2.4.0-cdh-6.2.3 is not supported.

**Comment by JamesBonddu** [comment]
谢谢，已处理。
