### ISSUE TITLE
Mac VSCode版本notebook运行报错

### ISSUE THREAD

**Issue by Mrhs121** [byzer-org/kolo-lang#1631]
Error: 
	at MLSQLNotebookController._doExecution (.vscode/extensions/allwefantasy.mlsql-0.0.5/dist/extension-node.js:24289:90)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by allwefantasy** [comment]
Try 0.0.7 http://download.mlsql.tech/byzer-lang-mac-0.0.7.vsix

**Comment by chncaesar** [comment]
@Mrhs121  Could you please try [release-2.2.1  Mac VsCode ](https://download.byzer.org/byzer/2.2.1/byzer-lang-darwin-0.0.7.vsix) , and let us know if the problem persists.
